function PlacesList()
{
this.Items = [
	{
		Name : 'Ресторан Томми Lee',
		OfSiteLink : 'http://tommilee.ru/',
		MenuLink : 'http://tommilee.ru/upload/iblock/c92/%D0%BC%D0%B5%D0%BD%D1%8E%20%D1%82%D0%BE%D0%BC%D0%BC%D0%B8_%20(1).pdf',
		LunchLink : '',
		WineLink : 'http://tommilee.ru/upload/iblock/ddd/Tomme_lee_%D0%BA%D0%BE%D0%BA%D1%82%D0%B5%D0%B9%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D0%BA%D0%B0%D1%80%D1%82%D0%B0_madyar.pdf',
		BeerLink : 'http://tommilee.ru/upload/iblock/ddd/Tomme_lee_%D0%BA%D0%BE%D0%BA%D1%82%D0%B5%D0%B9%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D0%BA%D0%B0%D1%80%D1%82%D0%B0_madyar.pdf',
		CocktailsLink : 'http://tommilee.ru/upload/iblock/ddd/Tomme_lee_%D0%BA%D0%BE%D0%BA%D1%82%D0%B5%D0%B9%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D0%BA%D0%B0%D1%80%D1%82%D0%B0_madyar.pdf',
		CoffeeLink : 'http://tommilee.ru/upload/iblock/ddd/Tomme_lee_%D0%BA%D0%BE%D0%BA%D1%82%D0%B5%D0%B9%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D0%BA%D0%B0%D1%80%D1%82%D0%B0_madyar.pdf',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d6941966-Reviews-Tommi_Lee-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'http://tommilee.ru/upload/iblock/31b/%D0%BC%D0%B5%D0%BD%D1%8E%20%D1%82%D0%BE%D0%BC%D0%BC%D0%B8_%20(1).pdf',
		Soup : 'http://tommilee.ru/upload/iblock/31b/%D0%BC%D0%B5%D0%BD%D1%8E%20%D1%82%D0%BE%D0%BC%D0%BC%D0%B8_%20(1).pdf',
		Breakfast : '',
		Dessert : '',
		Address : 'Кубанская наб., 1',
		District : '',
		WorkTime : 'пн-чт 12:00–1:00; пт,сб 12:00–2:00; вс 12:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'URBAN PUB',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/club55857414',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/urban_pub_krasnodar/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Северная ул., 354',
		District : '',
		WorkTime : 'пн-чт 17:00–1:00; пт,сб 17:00–2:00; вс 17:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Рыбный ресторан Royal Crab ',
		OfSiteLink : 'http://royal-crab.ru/',
		MenuLink : 'http://royal-crab.ru/',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'http://royal-crab.ru/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d14029571-Reviews-Royal_Crab-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/bar_royal_crab/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'http://royal-crab.ru/',
		Breakfast : '',
		Dessert : '',
		Address : 'Восточно-Кругликовская ул., 30/2, ',
		District : '',
		WorkTime : 'пн-чт 12:00–0:00; пт,сб 12:00–2:00; вс 12:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар", "Кафе", "Ресторан", "Пивнуха"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'McKey',
		OfSiteLink : 'http://mckeypub.com/',
		MenuLink : 'http://mckeypub.com/menu.pdf',
		LunchLink : '',
		WineLink : 'http://mckeypub.com/menu_vina.pdf',
		BeerLink : 'http://mckeypub.com/menyu/pivo',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d2664754-Reviews-McKey_Pub_Restaurant-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/mckey_pub/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'http://mckeypub.com/menu.pdf',
		Soup : 'http://mckeypub.com/menu.pdf',
		Breakfast : 'http://mckeypub.com/menu.pdf',
		Dessert : 'http://mckeypub.com/menu.pdf',
		Address : 'ул. Красных Партизан, 218, ',
		District : '',
		WorkTime : 'пн-ср 12:00–0:00; чт 10:00–0:00; пт,сб 10:00–2:00; вс 10:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар", "Кафе", "Ресторан", "БутКрафт"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Паб Ölster local pub',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.instagram.com/stories/highlights/17898795598283115/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/olsterpub/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Ставропольская ул., 133',
		District : '',
		WorkTime : 'пн-чт 17:00–1:00; пт 17:00–2:00; сб,вс 14:00–2:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар", "Кафе", "БутКрафт"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Шерлок Холмс Паб',
		OfSiteLink : 'http://holmespub.net/',
		MenuLink : 'http://holmespub.net/menu/',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'http://holmespub.net/menu/beer/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/holmespub',
		TripadvisorLink : '',
		InstaLink : 'https://vk.com/holmespub',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'http://holmespub.net/menu/stakes/',
		Soup : 'http://holmespub.net/menu/first-course/',
		Breakfast : '',
		Dessert : '',
		Address : 'Карасунская ул., 80',
		District : '',
		WorkTime : 'пн-чт 12:00–1:00; пт,сб 12:00–2:00; вс 12:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Grey Bear pub',
		OfSiteLink : 'https://www.greybear.pub',
		MenuLink : 'https://www.greybear.pub/food',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.greybear.pub/drinks',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'https://www.greybear.pub/food',
		Soup : 'https://www.greybear.pub/food',
		Breakfast : '',
		Dessert : '',
		Address : 'Красная ул., 67А',
		District : '',
		WorkTime : 'пн-чт 13:00–0:00; пт,сб 13:00–2:00; вс 13:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар", "Кафе", "Крафтбар", "БутКрафт"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Хмельной Дом "Митрополис"',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/hmelnoi_dom/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'ул. Ленина, 28А, Тульский',
		District : '',
		WorkTime : '11:00–22:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["БутКрафт"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Якитория',
		OfSiteLink : 'https://yakitoriya.ru/',
		MenuLink : 'https://yakitoriya.ru/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://yakitoriya.ru/menu-dostavki/supy',
		Breakfast : '',
		Dessert : 'https://yakitoriya.ru/menu-dostavki/deserty',
		Address : 'Красная ул., 72',
		District : '',
		WorkTime : '10:00–6:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Авторское кафе «Клумба»',
		OfSiteLink : 'http://steakhousegroup.com/klumba/o-kafe',
		MenuLink : 'http://steakhousegroup.com/klumba/menu',
		LunchLink : '',
		WineLink : 'http://steakhousegroup.com/klumba/menu#%D0%B2%D0%B8%D0%BD%D0%BD%D0%B0%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%B0',
		BeerLink : 'http://steakhousegroup.com/klumba/menu#%D0%B1%D0%B0%D1%80%D0%BD%D0%B0%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%B0',
		CocktailsLink : '',
		CoffeeLink : 'http://steakhousegroup.com/klumba/menu#%D0%B1%D0%B0%D1%80%D0%BD%D0%B0%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%B0',
		TeeLink : 'http://steakhousegroup.com/klumba/menu#%D0%B1%D0%B0%D1%80%D0%BD%D0%B0%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%B0',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'http://steakhousegroup.com/klumba/menu#%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B5-%D0%BC%D0%B5%D0%BD%D1%8E',
		Breakfast : 'http://steakhousegroup.com/klumba/menu#%D0%B7%D0%B0%D0%B2%D1%82%D1%80%D0%B0%D0%BA%D0%B8',
		Dessert : 'http://steakhousegroup.com/klumba/menu#%D0%B4%D0%B5%D1%81%D0%B5%D1%80%D1%82%D1%8B',
		Address : 'Октябрьская ул., 25/1',
		District : '',
		WorkTime : 'пн-пт 8:00–0:00; сб,вс 10:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан Тануки',
		OfSiteLink : 'https://krasnodar.tanuki.ru/restaurants/61/',
		MenuLink : 'https://krasnodar.tanuki.ru/menu/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d3767668-Reviews-Tanuki-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://krasnodar.tanuki.ru/menu/soup/',
		Breakfast : '',
		Dessert : '',
		Address : 'Ставропольская ул., 177/1',
		District : '',
		WorkTime : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе", "Ресторан"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан аргентинской кухни La Vaca',
		OfSiteLink : 'https://tomesto.ru/krasnodar/places/la-vaca',
		MenuLink : 'https://tomesto.ru/krasnodar/places/la-vaca',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'http://lavaca.ru/bar',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'https://tomesto.ru/krasnodar/places/la-vaca',
		Soup : 'https://tomesto.ru/krasnodar/places/la-vaca',
		Breakfast : '',
		Dessert : 'https://tomesto.ru/krasnodar/places/la-vaca',
		Address : '',
		District : '',
		WorkTime : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Чешская пивница ',
		OfSiteLink : 'http://krasnodar.pitnica.ru/',
		MenuLink : '',
		LunchLink : '',
		WineLink : 'http://krasnodar.pitnica.ru/menyu/',
		BeerLink : 'http://krasnodar.pitnica.ru/menyu/',
		CocktailsLink : 'http://krasnodar.pitnica.ru/menyu/',
		CoffeeLink : 'http://krasnodar.pitnica.ru/menyu/',
		TeeLink : 'http://krasnodar.pitnica.ru/menyu/',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/pitnica_krd/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'http://krasnodar.pitnica.ru/menyu/',
		Soup : 'http://krasnodar.pitnica.ru/menyu/',
		Breakfast : '',
		Dessert : 'http://krasnodar.pitnica.ru/menyu/',
		Address : 'Красная ул., 74',
		District : '',
		WorkTime : 'пн-чт 12:00–0:00; пт,сб 12:00–2:00; вс 12:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Пивбар", "Крафтбар", "БутКрафт", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Кафе «Холостяк - Романтики»',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/holostyak_romantiki',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d6025001-Reviews-Kholostyak_Romantiki-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Красная ул., 74',
		District : '',
		WorkTime : 'круглосуточно',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Пивбар", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Якитория',
		OfSiteLink : 'https://yakitoriya.ru/',
		MenuLink : 'https://yakitoriya.ru/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://yakitoriya.ru/menu-dostavki/supy',
		Breakfast : '',
		Dessert : 'https://yakitoriya.ru/menu-dostavki/deserty',
		Address : 'Ставропольская ул., 140',
		District : '',
		WorkTime : 'пн-чт 8:00–0:00; пт,сб 8:00–2:00; вс 8:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : '"Бельгиец" Брассерия.',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : 'https://vk.com/doc-162850416_464269186?dl=f240debc31a35ff024',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/belgiec_krd',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/belgiec_krd/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'улица Карасунская, 82/2',
		District : '',
		WorkTime : 'Понедельник- Четверг с 12:00 до 24:00,<br>Пятница с 12:00 до 02:00,<br>Суббота с 14:00 до 02:00,<br>Воскресенье с 14:00 до 24:00.',
		FoodType : ["Бельгийская"],
		TypeDelivery : [],
		DosugType : ["Клуббар", "Спортбар", "Пивбар", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Устричный бар Oysters',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d12995616-Reviews-Bar_Oysters-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/oysters_krd/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Рашпилевская ул., 101',
		District : '',
		WorkTime : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Ресторан"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан Стейкхаус парк',
		OfSiteLink : 'http://steakhousegroup.com/steakhousepark/about',
		MenuLink : 'http://steakhousegroup.com/steakhousepark/menu',
		LunchLink : '',
		WineLink : 'http://steakhousegroup.com/steakhousepark/menu#%D0%B1%D0%B0%D1%80%D0%BD%D0%B0%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%B0',
		BeerLink : 'http://steakhousegroup.com/steakhousepark/menu#%D0%B1%D0%B0%D1%80%D0%BD%D0%B0%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%B0',
		CocktailsLink : '',
		CoffeeLink : 'http://steakhousegroup.com/steakhousepark/menu#%D0%BD%D0%B0%D0%BF%D0%B8%D1%82%D0%BA%D0%B8-%D1%87%D0%B0%D0%B9-%D0%BA%D0%BE%D1%84%D0%B5',
		TeeLink : 'http://steakhousegroup.com/steakhousepark/menu#%D0%BD%D0%B0%D0%BF%D0%B8%D1%82%D0%BA%D0%B8-%D1%87%D0%B0%D0%B9-%D0%BA%D0%BE%D1%84%D0%B5',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'http://steakhousegroup.com/steakhousepark/menu#%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B5-%D0%BC%D0%B5%D0%BD%D1%8E',
		Soup : 'http://steakhousegroup.com/steakhousepark/menu#%D0%BF%D0%B5%D1%80%D0%B2%D1%8B%D0%B5-%D0%B1%D0%BB%D1%8E%D0%B4%D0%B0-%D0%B3%D0%BE%D1%80%D1%8F%D1%87%D0%B8%D0%B5-%D0%B7%D0%B0%D0%BA%D1%83%D1%81%D0%BA%D0%B8',
		Breakfast : '',
		Dessert : 'http://steakhousegroup.com/steakhousepark/menu#%D0%B4%D0%B5%D1%81%D0%B5%D1%80%D1%82%D1%8B',
		Address : 'ул. Александра Покрышкина, 34',
		District : '',
		WorkTime : '10:00–22:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Ресторан"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан Макароны ',
		OfSiteLink : 'http://macaroni.restaurant/',
		MenuLink : 'https://drive.google.com/file/d/1xrmNN7Vx6qKhtRq6Vz3CwibmJBBzMwkQ/view',
		LunchLink : '',
		WineLink : 'https://drive.google.com/file/d/1xrmNN7Vx6qKhtRq6Vz3CwibmJBBzMwkQ/view',
		BeerLink : 'https://drive.google.com/file/d/1xrmNN7Vx6qKhtRq6Vz3CwibmJBBzMwkQ/view',
		CocktailsLink : 'https://drive.google.com/file/d/1xrmNN7Vx6qKhtRq6Vz3CwibmJBBzMwkQ/view',
		CoffeeLink : 'https://drive.google.com/file/d/1xrmNN7Vx6qKhtRq6Vz3CwibmJBBzMwkQ/view',
		TeeLink : 'https://drive.google.com/file/d/1xrmNN7Vx6qKhtRq6Vz3CwibmJBBzMwkQ/view',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d10358899-Reviews-Makarony-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'https://drive.google.com/file/d/1xrmNN7Vx6qKhtRq6Vz3CwibmJBBzMwkQ/view',
		Soup : 'https://drive.google.com/file/d/1xrmNN7Vx6qKhtRq6Vz3CwibmJBBzMwkQ/view',
		Breakfast : 'https://drive.google.com/file/d/1xrmNN7Vx6qKhtRq6Vz3CwibmJBBzMwkQ/view',
		Dessert : 'https://drive.google.com/file/d/1xrmNN7Vx6qKhtRq6Vz3CwibmJBBzMwkQ/view',
		Address : 'ул. Соколова, 82',
		District : '',
		WorkTime : 'пн-чт 7:30–0:00; пт,сб 7:30–1:00; вс 7:30–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар", "Кафе", "Ресторан"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан Древний Пекин',
		OfSiteLink : '',
		MenuLink : 'https://www.instagram.com/stories/highlights/18051509680017001/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://www.instagram.com/stories/highlights/18051509680017001/',
		Breakfast : '',
		Dessert : 'https://www.instagram.com/stories/highlights/18051509680017001/',
		Address : 'ул. Фрунзе, 105 ',
		District : '',
		WorkTime : '12:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Бар Hop Dog',
		OfSiteLink : '',
		MenuLink : 'https://www.instagram.com/stories/highlights/17950549210139410/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/hopdogpub',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d12997768-Reviews-Hop_Dog_Pub-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/hopdogpub/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Восточно-Кругликовская ул., 18, ',
		District : '',
		WorkTime : 'пн-чт 12:00–1:00; пт,сб 12:00–3:00; вс 12:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Крафтбар", "Кафе", "БутКрафт", "Кикер"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Бар Бухаринъ',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/bukharin_krd/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Домбайская ул., 10/1',
		District : '',
		WorkTime : 'пн-чт 11:00–23:00; пт,сб 11:00–0:00; вс 11:00–23:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар", "Пивнуха"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Lounge Bar IL GARAGE ',
		OfSiteLink : 'http://il-garage.ru/',
		MenuLink : 'http://il-garage.ru/#menu-8',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'http://il-garage.ru/#menu-4',
		CocktailsLink : '',
		CoffeeLink : 'http://il-garage.ru/#menu-3',
		TeeLink : 'http://il-garage.ru/#menu-2',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/ilgarage_lounge',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'http://il-garage.ru/#menu-10',
		Breakfast : '',
		Dessert : '',
		Address : 'Новокузнечная ул., 34/1',
		District : '',
		WorkTime : 'пн-чт 13:00–1:00; пт,сб 13:00–3:00; вс 13:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кальянбар", "БутКрафт", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Бар 13 Rules',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/13rules_krasnodar',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/13rules_krasnodar/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Красноармейская ул., 73',
		District : '',
		WorkTime : 'пн-чт 12:00–2:00; пт,сб 12:00–6:00; вс 12:00–2:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Пивбар", "Крафтбар", "БутКрафт"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Duxless bar',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.instagram.com/stories/highlights/18046812250180098/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/duxless_bar/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'ул. Мира, 44',
		District : '',
		WorkTime : '11:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Пивбар", "Крафтбар", "БутКрафт", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'DONUTS & COFFEE',
		OfSiteLink : '',
		MenuLink : 'https://odonuts.coffee/catalog/osnovnoe/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/donutsandcoffee',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/donutscoffee.ru/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://odonuts.coffee/catalog/supy/',
		Breakfast : 'https://odonuts.coffee/catalog/zavtraki/',
		Dessert : '',
		Address : '',
		District : '',
		WorkTime : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Доставка"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Бар Большая рыба',
		OfSiteLink : '',
		MenuLink : 'https://bigfish.eat-and-trip.ru/menu/kuhnya',
		LunchLink : '',
		WineLink : 'https://bigfish.eat-and-trip.ru/menu/bar/igristie-vina',
		BeerLink : 'https://bigfish.eat-and-trip.ru/menu/bar/pivo',
		CocktailsLink : '',
		CoffeeLink : 'https://bigfish.eat-and-trip.ru/menu/bar/kofe',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://bigfish.eat-and-trip.ru/menu/kuhnya/pervie-blyuda',
		Breakfast : '',
		Dessert : '',
		Address : 'Жлобы, 137',
		District : '',
		WorkTime : 'пн-чт 12:00–2:00; пт,сб 12:00–4:00; вс 12:00–2:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Пивбар", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан «Порто Каррас»',
		OfSiteLink : '',
		MenuLink : 'https://porto-krd.ru/menu',
		LunchLink : '',
		WineLink : 'https://porto-krd.ru/menu',
		BeerLink : 'https://porto-krd.ru/menu',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : 'https://porto-krd.ru/menu',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d15609929-Reviews-Porto_Carras-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://porto-krd.ru/menu',
		Breakfast : '',
		Dessert : 'https://porto-krd.ru/menu',
		Address : 'Рашпилевская, 30/1',
		District : '',
		WorkTime : '10:00 - 23:30',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Ресторан"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Пражечка',
		OfSiteLink : '',
		MenuLink : 'http://prazacka.rest/menu.html',
		LunchLink : '',
		WineLink : 'https://www.instagram.com/stories/highlights/17970434884072522/',
		BeerLink : 'https://www.instagram.com/stories/highlights/17970434884072522/',
		CocktailsLink : '',
		CoffeeLink : 'https://www.instagram.com/stories/highlights/17876135497220844/',
		TeeLink : 'https://www.instagram.com/stories/highlights/17876135497220844/',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d8823036-Reviews-Prazhachka-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/prazacka_krasnodar/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'https://www.instagram.com/stories/highlights/17980207537088595/',
		Soup : 'https://www.instagram.com/stories/highlights/17876135497220844/',
		Breakfast : '',
		Dessert : 'https://www.instagram.com/stories/highlights/17876135497220844/',
		Address : 'Красноармейская ул., 43',
		District : '',
		WorkTime : '12:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Кафе Хорошая Еда',
		OfSiteLink : '',
		MenuLink : 'https://www.instagram.com/stories/highlights/17871186370446260/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : 'https://www.instagram.com/stories/highlights/17871186370446260/',
		TeeLink : 'https://www.instagram.com/stories/highlights/17871186370446260/',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d14178770-Reviews-Khoroshaya_Yeda-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/horoshaya_eda_/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://www.instagram.com/stories/highlights/17871186370446260/',
		Breakfast : '',
		Dessert : 'https://www.instagram.com/stories/highlights/17853587080662956/',
		Address : 'ул. Будённого, 129',
		District : '',
		WorkTime : 'пн-пт 8:00–22:00; сб,вс 9:00–22:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'кафе Bali Yummy',
		OfSiteLink : '',
		MenuLink : 'https://www.instagram.com/stories/highlights/17862048640550339/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d13318185-Reviews-Bali_Yummy-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/baliyummycafe/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://www.instagram.com/stories/highlights/17862048640550339/',
		Breakfast : '',
		Dessert : 'https://www.instagram.com/stories/highlights/17951031088038850/',
		Address : 'Карасунская ул., 77/1',
		District : '',
		WorkTime : '11:00–22:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Питчер паб',
		OfSiteLink : 'https://www.pitcher.pub/krasnodar/index.html',
		MenuLink : 'http://pitcher.pub/krasnodar/menu_food.html',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'http://pitcher.pub/krasnodar/menu_beer_draft.html',
		CocktailsLink : '',
		CoffeeLink : 'http://pitcher.pub/krasnodar/menu_food.html',
		TeeLink : 'http://pitcher.pub/krasnodar/menu_food.html',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/pitcherpub_krd',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d12288783-Reviews-Pitcher_Pub-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/pitcherpub_krd/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'http://pitcher.pub/krasnodar/menu_food.html',
		Soup : 'http://pitcher.pub/krasnodar/menu_food.html',
		Breakfast : '',
		Dessert : 'http://pitcher.pub/krasnodar/menu_food.html',
		Address : 'Красная ул., 68',
		District : '',
		WorkTime : 'пн-чт 12:00–0:00; пт,сб 12:00–3:00; вс 12:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Пивбар", "Крафтбар", "БутКрафт", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Пивной бар "ICEBEERG"',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/p/B2RwhgenW8z/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'ул. Селезнёва, 4А',
		District : '',
		WorkTime : 'Пн-Чт 12:00 23:00<br>Пт-Вс 12:00 00:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар", "Крафтбар", "Пивнуха"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Золотая лихорадка',
		OfSiteLink : '',
		MenuLink : 'http://zolotaya-lihoradka.ru/%D0%9C%D0%B5%D0%BD%D1%8E/',
		LunchLink : '',
		WineLink : 'https://tomesto.ru/krasnodar/places/zolotaya-lihoradka?utm_medium=cpc&utm_source=yandex&utm_campaign=krasnodar_restorany_y_poisk&utm_term=%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%B0%D1%8F%20%D0%BB%D0%B8%D1%85%D0%BE%D1%80%D0%B0%D0%B4%D0%BA%D0%B0%20%D0%BA%D1%80%D0',
		BeerLink : 'https://tomesto.ru/krasnodar/places/zolotaya-lihoradka?utm_medium=cpc&utm_source=yandex&utm_campaign=krasnodar_restorany_y_poisk&utm_term=%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%B0%D1%8F%20%D0%BB%D0%B8%D1%85%D0%BE%D1%80%D0%B0%D0%B4%D0%BA%D0%B0%20%D0%BA%D1%80%D0',
		CocktailsLink : 'https://tomesto.ru/krasnodar/places/zolotaya-lihoradka?utm_medium=cpc&utm_source=yandex&utm_campaign=krasnodar_restorany_y_poisk&utm_term=%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%B0%D1%8F%20%D0%BB%D0%B8%D1%85%D0%BE%D1%80%D0%B0%D0%B4%D0%BA%D0%B0%20%D0%BA%D1%80%D0',
		CoffeeLink : 'https://tomesto.ru/krasnodar/places/zolotaya-lihoradka?utm_medium=cpc&utm_source=yandex&utm_campaign=krasnodar_restorany_y_poisk&utm_term=%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%B0%D1%8F%20%D0%BB%D0%B8%D1%85%D0%BE%D1%80%D0%B0%D0%B4%D0%BA%D0%B0%20%D0%BA%D1%80%D0',
		TeeLink : 'https://tomesto.ru/krasnodar/places/zolotaya-lihoradka?utm_medium=cpc&utm_source=yandex&utm_campaign=krasnodar_restorany_y_poisk&utm_term=%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%B0%D1%8F%20%D0%BB%D0%B8%D1%85%D0%BE%D1%80%D0%B0%D0%B4%D0%BA%D0%B0%20%D0%BA%D1%80%D0',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/lihoradka_k',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d6031406-Reviews-Zolotaya_Likhoradka-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/zolotaya_lixoradka/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'https://tomesto.ru/krasnodar/places/zolotaya-lihoradka?utm_medium=cpc&utm_source=yandex&utm_campaign=krasnodar_restorany_y_poisk&utm_term=%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%B0%D1%8F%20%D0%BB%D0%B8%D1%85%D0%BE%D1%80%D0%B0%D0%B4%D0%BA%D0%B0%20%D0%BA%D1%80%D0',
		Soup : 'https://tomesto.ru/krasnodar/places/zolotaya-lihoradka?utm_medium=cpc&utm_source=yandex&utm_campaign=krasnodar_restorany_y_poisk&utm_term=%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%B0%D1%8F%20%D0%BB%D0%B8%D1%85%D0%BE%D1%80%D0%B0%D0%B4%D0%BA%D0%B0%20%D0%BA%D1%80%D0',
		Breakfast : 'http://zolotaya-lihoradka.ru/%D0%9C%D0%B5%D0%BD%D1%8E/',
		Dessert : 'https://tomesto.ru/krasnodar/places/zolotaya-lihoradka?utm_medium=cpc&utm_source=yandex&utm_campaign=krasnodar_restorany_y_poisk&utm_term=%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%B0%D1%8F%20%D0%BB%D0%B8%D1%85%D0%BE%D1%80%D0%B0%D0%B4%D0%BA%D0%B0%20%D0%BA%D1%80%D0',
		Address : 'Кубанская наб., 23',
		District : '',
		WorkTime : 'пн-чт 11:00–1:00; пт,сб 11:00–5:00; вс 11:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Ресторан"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан Голый повар',
		OfSiteLink : 'https://nakedchef.ru/',
		MenuLink : 'http://nakedchef.ru/images/menu030719.pdf',
		LunchLink : '',
		WineLink : 'https://nakedchef.ru/images/menu030719.pdf',
		BeerLink : 'http://nakedchef.ru/images/menu030719.pdf',
		CocktailsLink : 'https://nakedchef.ru/images/menu030719.pdf',
		CoffeeLink : 'https://nakedchef.ru/images/menu030719.pdf',
		TeeLink : 'https://nakedchef.ru/images/menu030719.pdf',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/nakedchef.ru/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'https://nakedchef.ru/images/menu030719.pdf',
		Soup : 'https://nakedchef.ru/images/menu030719.pdf',
		Breakfast : '',
		Dessert : 'https://nakedchef.ru/images/menu030719.pdf',
		Address : '',
		District : '',
		WorkTime : 'пн-чт 12:00–0:00; пт,сб 12:00–2:00; вс 12:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : [],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан Бумбараш',
		OfSiteLink : 'http://mandarinfamily.ru/page/CID_2.html',
		MenuLink : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/bk/bk.pdf',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/bk/bk.pdf;Heineken 390',
		CocktailsLink : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/bk/bk.pdf',
		CoffeeLink : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/bk/bk.pdf',
		TeeLink : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/bk/bk.pdf',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/bk/bk.pdf',
		Breakfast : '',
		Dessert : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/bk/bk.pdf',
		Address : 'Красная ул., 143/3',
		District : '',
		WorkTime : 'пн-чт 9:00–0:00; пт,сб 9:00–2:00; вс 9:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан Стейкхаус',
		OfSiteLink : '',
		MenuLink : 'http://steakhousegroup.com/steakhouse/menu',
		LunchLink : '',
		WineLink : 'http://steakhousegroup.com/steakhouse/menu#%D0%B2%D0%B8%D0%BD%D0%BD%D0%B0%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%B0',
		BeerLink : 'http://steakhousegroup.com/steakhouse/menu#%D0%BD%D0%B0%D0%BF%D0%B8%D1%82%D0%BA%D0%B8',
		CocktailsLink : 'http://steakhousegroup.com/steakhouse/menu#%D0%BA%D0%BE%D0%BA%D1%82%D0%B5%D0%B9%D0%BB%D0%B8',
		CoffeeLink : 'http://steakhousegroup.com/steakhouse/menu#%D0%BA%D0%BE%D1%84%D0%B5',
		TeeLink : 'http://steakhousegroup.com/steakhouse/menu#%D1%87%D0%B0%D0%B9',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'http://steakhousegroup.com/steakhouse/menu#%D1%81%D1%82%D0%B5%D0%B9%D0%BA%D0%B8',
		Soup : 'http://steakhousegroup.com/steakhouse/menu#%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B5-%D0%BC%D0%B5%D0%BD%D1%8E',
		Breakfast : '',
		Dessert : 'http://steakhousegroup.com/steakhouse/menu#%D0%B4%D0%B5%D1%81%D0%B5%D1%80%D1%82%D1%8B',
		Address : 'Октябрьская ул., 27/1',
		District : '',
		WorkTime : '11:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Ресторан"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Мясной ресторан Скотина',
		OfSiteLink : 'https://scotina.ru/',
		MenuLink : 'https://scotina.ru/wp-content/uploads/2018/12/Skotina_kuhnya_dekabr_.pdf',
		LunchLink : '',
		WineLink : 'https://scotina.ru/wp-content/uploads/2018/12/Skotina-alkogol_dekabr-2019_.pdf',
		BeerLink : 'https://scotina.ru/wp-content/uploads/2018/12/Skotina-alkogol_dekabr-2019_.pdf',
		CocktailsLink : 'https://scotina.ru/wp-content/uploads/2019/03/koktejlnaya_karta_skotina-2.pdf',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/scotinarestoran',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d5498712-Reviews-Skotina_Meat_Restaurant-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/scotina_krd/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'https://scotina.ru/wp-content/uploads/2018/12/Skotina_kuhnya_dekabr_.pdf',
		Soup : 'https://scotina.ru/wp-content/uploads/2018/12/Skotina_kuhnya_dekabr_.pdf',
		Breakfast : '',
		Dessert : 'https://scotina.ru/wp-content/uploads/2018/12/Skotina_kuhnya_dekabr_.pdf',
		Address : 'ул. Суворова',
		District : '',
		WorkTime : 'пн-чт 12:00–0:00; пт,сб 12:00–1:00; вс 12:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Крафтбар", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Крафтовый паб Kulibin pub',
		OfSiteLink : '',
		MenuLink : 'https://www.kulibin.pub/menu',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.kulibin.pub/craft-beer',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'https://www.kulibin.pub/menu',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Карасунская ул., 83,',
		District : '',
		WorkTime : 'пн-чт 15:00–1:00; пт,сб 15:00–3:00; вс 15:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Клуббар", "Крафтбар", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Big Village Brewery & Taproom',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://www.facebook.com/bigvillagebrewery',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/big_village_brew/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'ул. Стасова, 182/1',
		District : '',
		WorkTime : 'пн-чт 13:00–22:00; пт,сб 13:00–0:00; вс 13:00–22:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Крафтбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Бар крафтового пива Декабрист ',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/dekabristkrd',
		TripadvisorLink : 'https://www.tripadvisor.ru/Attraction_Review-g298532-d10154041-Reviews-Bar_Dekabrist-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/dekabrist_krd/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Карасунская ул., 82/2',
		District : '',
		WorkTime : 'пн-чт 15:00–0:00; пт,сб 15:00–2:00; вс 15:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Пивбар", "Крафтбар", "БутКрафт"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан Чо-Чо',
		OfSiteLink : 'http://restoran-cho.ru/',
		MenuLink : 'http://restoran-cho.ru/menu/',
		LunchLink : '',
		WineLink : 'http://restoran-cho.ru/upload/iblock/fce/_.pdf',
		BeerLink : 'http://restoran-cho.ru/upload/iblock/fce/_.pdf',
		CocktailsLink : 'http://restoran-cho.ru/upload/iblock/fce/_.pdf',
		CoffeeLink : 'http://restoran-cho.ru/upload/iblock/fce/_.pdf',
		TeeLink : 'http://restoran-cho.ru/upload/iblock/fce/_.pdf',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/34chocho',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d8759964-Reviews-Restaurant_Cho_Cho-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/chochorest/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'http://restoran-cho.ru/upload/iblock/33d/steaks_menu.pdf',
		Soup : 'http://restoran-cho.ru/upload/iblock/3ca/_-_.pdf',
		Breakfast : '',
		Dessert : '',
		Address : 'Дальняя ул., 41/1',
		District : '',
		WorkTime : 'пн-чт 12:00–1:00; пт,сб 12:00–6:00; вс 12:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Ресторан"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Барабулька',
		OfSiteLink : 'http://mandarinfamily.ru/page/CID_3.html',
		MenuLink : 'http://mandarinfamily.ru/upload/iblock/bc8/bc87fb36567de43c7788cff55187f025.pdf',
		LunchLink : '',
		WineLink : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/barabulka/barabulka.pdf',
		BeerLink : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/barabulka/barabulka.pdf',
		CocktailsLink : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/barabulka/barabulka.pdf',
		CoffeeLink : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/barabulka/barabulka.pdf',
		TeeLink : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/barabulka/barabulka.pdf',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/barabulkacafe',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d6024655-Reviews-Barabulka_afe-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : 'https://docs.google.com/viewer?url=https://mandarin.nateste.ru/menu/barabulka/barabulka.pdf',
		Address : 'Платановый бул., 17/1',
		District : '',
		WorkTime : 'пн-ср 12:00–2:00; чт 12:00–0:00; пт-вс 12:00–2:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Teppanyaki Bar',
		OfSiteLink : 'http://teppan-rest.ru/',
		MenuLink : 'http://expert-poisk.ru/data/teppanyaki_bar_menu_newone.pdf',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/teppanrestt',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/teppanrest/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'https://www.instagram.com/p/B3ErbO5IFJn/',
		Soup : 'https://www.instagram.com/p/B3ErbO5IFJn/',
		Breakfast : '',
		Dessert : 'https://www.instagram.com/p/B3ErbO5IFJn/',
		Address : 'Российская ул., 255/9',
		District : '',
		WorkTime : 'пн-чт 12:00–2:00; пт-вс 12:00–3:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Ресторан Чайка Ливингстон',
		OfSiteLink : '',
		MenuLink : 'https://livingstone.eat-and-trip.ru/menu',
		LunchLink : '',
		WineLink : 'https://livingstone.eat-and-trip.ru/menu',
		BeerLink : 'https://livingstone.eat-and-trip.ru/menu',
		CocktailsLink : 'https://livingstone.eat-and-trip.ru/menu',
		CoffeeLink : 'https://livingstone.eat-and-trip.ru/menu',
		TeeLink : 'https://livingstone.eat-and-trip.ru/menu',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://livingstone.eat-and-trip.ru/menu',
		Breakfast : 'https://livingstone.eat-and-trip.ru/menu',
		Dessert : 'https://livingstone.eat-and-trip.ru/menu',
		Address : 'Восточно-Кругликовская ул., 26',
		District : '',
		WorkTime : 'пн-чт 8:00–0:00; пт,сб 8:00–1:00; вс 8:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Кафе", "БутКрафт"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'DiR PUB',
		OfSiteLink : '',
		MenuLink : 'https://www.instagram.com/stories/highlights/17846574400630489/',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.instagram.com/stories/highlights/17846574400630489/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/dir_pub/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Промышленная ул., 88',
		District : '',
		WorkTime : 'чт 17:00–3:00; пт,сб 17:00–5:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Клуббар", "Пивнуха", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Hopkins Bar',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://www.facebook.com/hopkins.bar/',
		TripadvisorLink : 'https://www.tripadvisor.ru/Attraction_Review-g298532-d11803943-Reviews-Hopkins_Bar-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/hopkins_bar/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : '',
		Breakfast : '',
		Dessert : '',
		Address : 'Красная ул., 67/1',
		District : '',
		WorkTime : 'пн-пт 15:00–1:00; сб,вс 14:00–1:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Пивбар", "Пивнуха", "Крафтбар", "БутКрафт"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Macgregor’s Паб',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://www.facebook.com/macgregorspub/',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d19719035-Reviews-Macgregor_s-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/macgregors_pub/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'https://www.instagram.com/stories/highlights/18033586681227797/',
		Soup : 'https://www.instagram.com/stories/highlights/18033586681227797/',
		Breakfast : '',
		Dessert : 'https://www.instagram.com/stories/highlights/18033586681227797/',
		Address : 'Красная, 65',
		District : '',
		WorkTime : 'пн-чт 12:00–0:00; пт,сб 12:00–2:00; вс 12:00–0:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Пивбар", "Пивнуха", "Крафтбар", "БутКрафт", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Mr. Drunke Bar',
		OfSiteLink : '',
		MenuLink : 'http://www.drunkebar.ru/wp-content/uploads/2018/12/%D0%94%D1%80%D0%B0%D0%BD%D0%BA%D0%B5_%D0%BC%D0%B5%D0%BD%D1%8E_%D0%B5%D0%B4%D0%B0_%D0%BE%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8C_3-1.pdf',
		LunchLink : '',
		WineLink : 'http://www.drunkebar.ru/wp-content/uploads/2018/12/%D0%9C%D0%B5%D0%BD%D1%8E-%D0%BA%D1%80%D0%B5%D0%BF%D0%BA%D0%B8-%D0%B0%D0%BB-%D0%94%D1%80%D0%B0%D0%BD%D0%BA%D0%B8_%D0%B4%D0%B5%D0%BA%D0%B0%D0%B1%D1%80%D1%8C-2019.pdf',
		BeerLink : 'http://www.drunkebar.ru/wp-content/uploads/2018/12/%D0%94%D1%80%D0%B0%D0%BD%D0%BA%D0%B5_%D0%BC%D0%B5%D0%BD%D1%8E_%D0%BF%D0%B8%D0%B2%D0%BE_%D0%B8%D1%8E%D0%BB%D1%8C_new.pdf',
		CocktailsLink : 'http://www.drunkebar.ru/wp-content/uploads/2018/12/%D0%9C%D0%B5%D0%BD%D1%8E_%D0%BA%D0%BE%D0%BA%D1%82%D0%B5%D0%B8%CC%86%D0%BB%D0%B8_%D0%BE%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8C.pdf',
		CoffeeLink : 'http://www.drunkebar.ru/wp-content/uploads/2018/12/%D0%9C%D0%B5%D0%BD%D1%8E-%D0%BA%D1%80%D0%B5%D0%BF%D0%BA%D0%B8-%D0%B0%D0%BB-%D0%94%D1%80%D0%B0%D0%BD%D0%BA%D0%B8_%D0%B4%D0%B5%D0%BA%D0%B0%D0%B1%D1%80%D1%8C-2019.pdf',
		TeeLink : 'http://www.drunkebar.ru/wp-content/uploads/2018/12/%D0%9C%D0%B5%D0%BD%D1%8E-%D0%BA%D1%80%D0%B5%D0%BF%D0%BA%D0%B8-%D0%B0%D0%BB-%D0%94%D1%80%D0%B0%D0%BD%D0%BA%D0%B8_%D0%B4%D0%B5%D0%BA%D0%B0%D0%B1%D1%80%D1%8C-2019.pdf',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : 'https://vk.com/drunkebar',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298532-d6214816-Reviews-Mr_Drunke_Bar-Krasnodar_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/mr_drunkebar/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : 'http://www.drunkebar.ru/wp-content/uploads/2018/12/%D0%94%D1%80%D0%B0%D0%BD%D0%BA%D0%B5_%D0%BC%D0%B5%D0%BD%D1%8E_%D0%B5%D0%B4%D0%B0_%D0%BE%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8C_3-1.pdf',
		Soup : 'http://www.drunkebar.ru/wp-content/uploads/2018/12/%D0%94%D1%80%D0%B0%D0%BD%D0%BA%D0%B5_%D0%BC%D0%B5%D0%BD%D1%8E_%D0%B5%D0%B4%D0%B0_%D0%BE%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8C_3-1.pdf',
		Breakfast : 'http://www.drunkebar.ru/wp-content/uploads/2018/12/%D0%9C%D0%B5%D0%BD%D1%8E_%D0%BA%D0%BE%D0%BA%D1%82%D0%B5%D0%B8%CC%86%D0%BB%D0%B8_%D0%BE%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8C.pdf',
		Dessert : 'http://www.drunkebar.ru/wp-content/uploads/2018/12/%D0%94%D1%80%D0%B0%D0%BD%D0%BA%D0%B5_%D0%BC%D0%B5%D0%BD%D1%8E_%D0%B5%D0%B4%D0%B0_%D0%BE%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8C_3-1.pdf',
		Address : 'Красноармейская ул., 58',
		District : '',
		WorkTime : 'пн-чт 8:00–1:00; пт,сб 8:00–5:00; вс 10:00–2:00',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Крафтбар", "БутКрафт", "Пивбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},	{
		Name : 'Аригатор',
		OfSiteLink : '',
		MenuLink : 'https://eda123.ru/catalog/pizza/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Steaks : '',
		Soup : 'https://arigator.ru/catalog/supy/',
		Breakfast : 'https://arigator.ru/catalog/zavtraki/',
		Dessert : 'https://arigator.ru/catalog/sladkoe/',
		Address : '',
		District : '',
		WorkTime : 'вс-чт: 10:00 - 23:30<br>пт-сб: 10:00 - 00:30',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Доставка"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],
		Photos : [],

	},];
}
