function PlacesList()
{
this.Items = [
	{
		Name : 'Ресторан Бар "Драфт"',
		OfSiteLink : 'https://www.draftbarsochi.ru/',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/draftbeerbar/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.589868',
		Longitude : '39.724682',
		Video : '',
		AddressLink : '',
		Address : 'Навагинская ул., 11',
		District : 'Сочи',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Итальянская", "Пицца", "Европейская", "Русская", "Американская"],
		TypeDelivery : [],
		DosugType : ["Драфтбар", "Паб", "Ресторан", "Стейкхаус", "Бильярд", "Кикер", "Спортбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Ресторан Nippon House',
		OfSiteLink : '',
		MenuLink : 'https://www.instagram.com/stories/highlights/18042465112205624/',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.instagram.com/stories/highlights/18101632966076439/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/nipponhouse_sochi/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.422948',
		Longitude : '39.924094',
		Video : '',
		AddressLink : '',
		Address : 'Демократическая ул., 32',
		District : 'Адлер',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Японская", "Пицца", "Европейская", "Итальянская", "Роллы", "Паназиатская"],
		TypeDelivery : [],
		DosugType : ["Ресторан", "Драфтбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Ресторан Nippon House',
		OfSiteLink : '',
		MenuLink : 'https://www.instagram.com/stories/highlights/18042465112205624/',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.instagram.com/stories/highlights/18101632966076439/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/nipponhouse_sochi/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.589634',
		Longitude : '39.722595',
		Video : '',
		AddressLink : '',
		Address : 'ул. Воровского, 36',
		District : 'Сочи',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Японская", "Пицца", "Европейская", "Итальянская", "Роллы", "Паназиатская"],
		TypeDelivery : [],
		DosugType : ["Ресторан", "Драфтбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Ресторан «La Luna»',
		OfSiteLink : '',
		MenuLink : 'https://www.cafe-laluna.ru/menu/osnovnoe-menyu/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/laluna_adler/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.389611',
		Longitude : '39.984208',
		Video : '',
		AddressLink : '',
		Address : 'Таврическая ул., 1',
		District : 'Парк',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Итальянская", "Пицца", "Европейская", "Русская", "Американская", "Роллы", "Французская", "Паназиатская", "Средиземноморская"],
		TypeDelivery : [],
		DosugType : ["Ресторан"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Why Not крафтовое пиво ',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.instagram.com/p/B6QP8yip87S/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/whynotbar.mtn/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.683734',
		Longitude : '40.269072',
		Video : '',
		AddressLink : '',
		Address : 'ул. Эстонская, 97/3',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Крафтбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Гастрокомплекс КРАСНАЯ ПОЛЯНА ',
		OfSiteLink : '',
		MenuLink : 'https://www.instagram.com/stories/highlights/17848499809404867/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/cafekrasnayapolyana/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.672346',
		Longitude : '40.294232',
		Video : '',
		AddressLink : '',
		Address : 'наб. Панорама, 2,',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Русская", "Финская"],
		TypeDelivery : [],
		DosugType : ["Ресторан", "Стейкхаус"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Fettuccine Trattoria Сочи',
		OfSiteLink : 'https://fettuccine-t.ru',
		MenuLink : 'https://fettuccine-t.ru/menu',
		LunchLink : '',
		WineLink : 'https://fettuccine-t.ru/menu',
		BeerLink : 'https://fettuccine-t.ru/menu',
		CocktailsLink : 'https://fettuccine-t.ru/menu',
		CoffeeLink : 'https://fettuccine-t.ru/menu',
		TeeLink : 'https://fettuccine-t.ru/menu',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g298536-d6950120-Reviews-Trattoria_Fettuccine-Sochi_Greater_Sochi_Krasnodar_Krai_Southern_District.html',
		InstaLink : 'https://www.instagram.com/fettuccinesochi/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.573951',
		Longitude : '39.73155',
		Video : '',
		AddressLink : '',
		Address : 'Театральная ул., 11',
		District : 'Сочи',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Итальянская", "Пицца", "Европейская", "Русская"],
		TypeDelivery : [],
		DosugType : ["Ресторан"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Кафе Встреча',
		OfSiteLink : '',
		MenuLink : 'https://www.instagram.com/stories/highlights/17994350515255043/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/vstrechacafe.adler/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.423567',
		Longitude : '39.922108',
		Video : '',
		AddressLink : '',
		Address : 'ул. Кирова, 35',
		District : 'Адлер',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Итальянская", "Пицца", "Европейская", "Русская", "Финская"],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'HYGGE KAFE',
		OfSiteLink : 'http://hyggecafe.ru/',
		MenuLink : 'http://hyggecafe.ru/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.682416',
		Longitude : '40.212171',
		Video : '',
		AddressLink : '',
		Address : 'Волоколамская ул., 112',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Шведская", "Пицца", "Европейская", "Итальянская", "Финская", "Паназиатская"],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Сеть столовых «Ем и Ем» ',
		OfSiteLink : 'https://emiem.ru/',
		MenuLink : 'https://emiem.ru/catalog/supy',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '0',
		Longitude : '0',
		Video : '',
		AddressLink : '',
		Address : 'ул. Эстонская д. 117',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Русская", "Роллы"],
		TypeDelivery : [],
		DosugType : ["Доставка"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'SUSHIлка',
		OfSiteLink : '',
		MenuLink : 'https://sushilka.online/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g3206479-d15690818-Reviews-Sushilka-Esto_Sadok_Adler_District_Sochi_Greater_Sochi_Krasnodar_Krai_Southern_.html',
		InstaLink : 'https://www.instagram.com/sushilka_estosadok/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.685785',
		Longitude : '40.254045',
		Video : '',
		AddressLink : '',
		Address : 'Эстонская ул., 39',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Паназиатская", "Роллы"],
		TypeDelivery : [],
		DosugType : ["Доставка"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Bandido Bar Сочи',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.instagram.com/p/B96-B5doH7T/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/bandido_bar_sochi/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.589916',
		Longitude : '39.717268',
		Video : '',
		AddressLink : '',
		Address : 'ул. Чайковского',
		District : 'Сочи',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Крафтбар", "Бар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'ирландский паб harats сочи',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.instagram.com/stories/highlights/17859777142708696/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/haratspubsochi/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.568664',
		Longitude : '39.732231',
		Video : '',
		AddressLink : '',
		Address : 'Черноморская ул., 3, корп. 7,',
		District : 'Сочи',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Паб", "Спортбар", "Драфтбар", "Пивбар", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'BeBeer ',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/bebeer_sochi/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.584573',
		Longitude : '39.716049',
		Video : '',
		AddressLink : '',
		Address : 'Несебрская ул., 1Б',
		District : 'Сочи',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Крафтбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Добро Паб ',
		OfSiteLink : '',
		MenuLink : 'https://delivery.restik.com/dobro_burger',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.6858',
		Longitude : '40.254162',
		Video : '',
		AddressLink : '',
		Address : 'Эстонская ул., 39',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Русская", "Европейская", "Американская", "Паназиатская"],
		TypeDelivery : [],
		DosugType : ["Доставка", "Стейкхаус"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Берлога буфет & бар',
		OfSiteLink : 'http://www.berlogabar.ru/',
		MenuLink : 'http://www.berlogabar.ru/wp-content/uploads/2020/09/Berloga_sait_menu.pdf',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/berlogabar/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.658874',
		Longitude : '40.321099',
		Video : '',
		AddressLink : '',
		Address : 'ул. Урочище Ржаная Поляна, 1/37/1',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Русская", "Европейская", "Американская", "Паназиатская"],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Ресторан "Груша"',
		OfSiteLink : 'http://grusharest.ru/',
		MenuLink : 'http://grusharest.ru/#menu',
		LunchLink : '',
		WineLink : 'http://grusharest.ru/#menu',
		BeerLink : 'http://grusharest.ru/#menu',
		CocktailsLink : 'http://grusharest.ru/#menu',
		CoffeeLink : 'http://grusharest.ru/#menu',
		TeeLink : 'http://grusharest.ru/#menu',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/grusha_rest/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.659909',
		Longitude : '40.319587',
		Video : '',
		AddressLink : '',
		Address : 'ул. Медовея, 8/1',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Русская", "Пицца", "Американская"],
		TypeDelivery : [],
		DosugType : ["Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Ресторан Высота 2320',
		OfSiteLink : '',
		MenuLink : 'https://www.vysota2320.ru/menu/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/vysota2320/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.624328',
		Longitude : '40.313579',
		Video : '',
		AddressLink : '',
		Address : '',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Русская"],
		TypeDelivery : [],
		DosugType : ["Ресторан", "Стейкхаус"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'O Hara Pub',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : 'https://www.tripadvisor.ru/Restaurant_Review-g3206479-d7592620-Reviews-O_Hara_pub-Esto_Sadok_Adler_District_Sochi_Greater_Sochi_Krasnodar_Krai_Southern.html',
		InstaLink : 'https://www.instagram.com/ohara_rosakhutor/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.672624',
		Longitude : '40.291546',
		Video : '',
		AddressLink : '',
		Address : 'наб. Лаванда, 2',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Паб", "Спортбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Harats',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://www.instagram.com/stories/highlights/17859936862698229/',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/haratspubgorky/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.683717',
		Longitude : '40.260901',
		Video : '',
		AddressLink : '',
		Address : 'ул. Горная Карусель, 1',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Паб", "Спортбар", "Драфтбар", "Пивбар", "Кафе"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Трактир «Трикони»',
		OfSiteLink : 'https://trikoni.ru/',
		MenuLink : 'https://trikoni.ru/menyu-gastropaba/',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/traktir_trikoni/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.682743',
		Longitude : '40.215843',
		Video : '',
		AddressLink : '',
		Address : 'ул. Мичурина, 1',
		District : 'Красная поляна',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : ["Русская", "Европейская", "Итальянская", "Паназиатская"],
		TypeDelivery : [],
		DosugType : ["Ресторан", "Стейкхаус"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Бар "Сочинка"',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/pivnaya_sochinka/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.613584',
		Longitude : '39.742698',
		Video : '',
		AddressLink : '',
		Address : 'Абрикосовая ул., 2/6',
		District : 'Сочи',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Спортбар", "Крафт"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Английский паб "The Prince of Wales"',
		OfSiteLink : '',
		MenuLink : 'https://gruppaluxe.com/theprince',
		LunchLink : '',
		WineLink : '',
		BeerLink : 'https://gruppaluxe.com/theprince',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : '',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.411707',
		Longitude : '39.936895',
		Video : '',
		AddressLink : '',
		Address : 'Парусная ул., 39',
		District : 'Парк',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Паб", "Драфтбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},	{
		Name : 'Ирландский паб O Sullivan s',
		OfSiteLink : '',
		MenuLink : '',
		LunchLink : '',
		WineLink : '',
		BeerLink : '',
		CocktailsLink : '',
		CoffeeLink : '',
		TeeLink : '',
		WithAlcohol : '',
		KafeTaganrogLink : '',
		VkontakteLink : '',
		TripadvisorLink : '',
		InstaLink : 'https://www.instagram.com/osullivans_sochi/',
		UgostiLink : '',
		VirtualTaganrogLink : '',
		RestaurantguruLink : '',
		InfotaganrogLink : '',
		FoursquareLink : '',
		TraveltipzLink : '',
		LocalwayLink : '',
		CameraLink : '',
		TCLink : '',
		TCIconLink : '',
		SpravkerLink : '',
		UniquePhotoLink : '',
		Latitude : '43.396492',
		Longitude : '39.975269',
		Video : '',
		AddressLink : '',
		Address : 'ул. 65 лет Победы, 55',
		District : 'Парк',
		Phones : '',
		AverageBill : '',
		WorkTime : '',
		Services : '',
		AdditionalInfo : '',
		Cost : '',
		FoodType : [],
		TypeDelivery : [],
		DosugType : ["Паб", "Драфтбар", "Крафт", "Спортбар"],
		TypeKafe : [],
		BathType : [],
		Capacity : [],
		BilliardType : [],

	},];
}
